<!-- 
Excerpt from 
http://libphonenumber.googlecode.com/svn/trunk/resources/PhoneNumberMetadata.xml
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (availableFormats?, generalDesc?, noInternationalDialling?,
        areaCodeOptional?, fixedLine?, mobile?, pager?, tollFree?, premiumRate?,
        sharedCost?, personalNumber?, voip?, uan?, voicemail?)>
    <!ELEMENT generalDesc (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT noInternationalDialling (nationalNumberPattern, possibleNumberPattern?,
        exampleNumber?)>
    <!ELEMENT areaCodeOptional (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT fixedLine (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT mobile (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT pager (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT tollFree (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT premiumRate (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT sharedCost (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT personalNumber (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voip (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT uan (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voicemail (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT possibleNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>
    <!ELEMENT leadingDigits (#PCDATA)>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory mainCountryForCode (true) #IMPLIED>
    <!ATTLIST territory leadingDigits CDATA #IMPLIED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST territory leadingZeroPossible (true) #IMPLIED>
    <!ATTLIST territory carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory mobileNumberPortableRegion (true) #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST numberFormat carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Estonia -->
    <!-- http://www.itu.int/oth/T0202000043/en -->
    <!-- http://www.tja.ee/public/Legislation_side/Numbering_/Estonian_NP_eng.htm -->
    <territory id="EE" countryCode="372" internationalPrefix="00" mobileNumberPortableRegion="true">
      <availableFormats>
        <numberFormat pattern="([3-79]\d{2})(\d{4})">
          <leadingDigits>
            [369]|
            4[3-8]|
            5(?:
              [0-2]|
              5[0-478]|
              6[45]
            )|
            7[1-9]
          </leadingDigits>
          <leadingDigits>
            [369]|
            4[3-8]|
            5(?:
              [02]|
              1(?:
                [0-8]|
                95
              )|
              5[0-478]|
              6(?:
                4[0-4]|
                5[1-589]
              )
            )|
            7[1-9]
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(70)(\d{2})(\d{4})">
          <leadingDigits>70</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(8000)(\d{3})(\d{3})">
          <leadingDigits>800</leadingDigits>
          <leadingDigits>8000</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="([458]\d{3})(\d{3,4})">
          <leadingDigits>
            40|
            5|
            8(?:
              00|
              [1-5]
            )
          </leadingDigits>
          <leadingDigits>
            40|
            5|
            8(?:
              00[1-9]|
              [1-5]
            )
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          1\d{3,4}|
          [3-9]\d{6,7}|
          800\d{6,7}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{4,10}</possibleNumberPattern>
      </generalDesc>
      <noInternationalDialling>
        <nationalNumberPattern>
          1\d{3,4}|
          800[2-9]\d{3}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{4,7}</possibleNumberPattern>
        <exampleNumber>8002123</exampleNumber>
      </noInternationalDialling>
      <fixedLine>
        <!-- Supporting eFax numbers here as well. -->
        <nationalNumberPattern>
          (?:
            3[23589]|
            4(?:
              0\d|
              [3-8]
            )|
            6\d|
            7[1-9]|
            88
          )\d{5}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,8}</possibleNumberPattern>
        <exampleNumber>3212345</exampleNumber>
      </fixedLine>
      <mobile>
        <!-- 7 digit mobile numbers currently in use with special prefixes are preserved - new
             numbers are 8 digits. -->
        <nationalNumberPattern>
          (?:
            5\d|
            8[1-5]
          )\d{6}|
          5(?:
            [02]\d{2}|
            1(?:
              [0-8]\d|
              95
            )|
            5[0-478]\d|
            64[0-4]|
            65[1-589]
          )\d{3}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,8}</possibleNumberPattern>
        <exampleNumber>51234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>
          800(?:
            0\d{3}|
            1\d|
            [2-9]
          )\d{3}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,10}</possibleNumberPattern>
        <exampleNumber>80012345</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}</possibleNumberPattern>
        <exampleNumber>9001234</exampleNumber>
      </premiumRate>
      <personalNumber>
        <nationalNumberPattern>70[0-2]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{8}</possibleNumberPattern>
        <exampleNumber>70012345</exampleNumber>
      </personalNumber>
      <uan>
        <!-- All 4-5 digit numbers listed in the plan as being a "short number for a service" are
             included here. -->
        <nationalNumberPattern>
          1(?:
            2[01245]|
            3[0-6]|
            4[1-489]|
            5[0-59]|
            6[1-46-9]|
            7[0-27-9]|
            8[189]|
            9[012]
          )\d{1,2}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{4,5}</possibleNumberPattern>
        <exampleNumber>12123</exampleNumber>
      </uan>
    </territory>
  </territories>
</phoneNumberMetadata>
